import React from "react";
import Head from "next/head";
import { getProductsInCollection } from "../../lib/shopify";
import CollectionsDetails from "../../components/CollectionsDetails";

export default function collectionDetail({ collection }) {
  return (
    <>
      <Head>
        <title>Collections Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <CollectionsDetails collection={collection} />
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  const collection = await getProductsInCollection(context.params.collection);

  return {
    props: {
      collection,
    },
  };
}
