import React from "react";
import Head from "next/head";
import { getAllCollections } from "../../lib/shopify";
import CollectionsList from "../../components/CollectionsList";

export default function collections({ collections }) {
  return (
    <>
      <Head>
        <title>Collections</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CollectionsList collections={collections} />
      </main>
    </>
  );
}
// export async function getStaticProps() {
//   const collections = await getAllCollections();

//   return {
//     props: { collections },
//   };
// }
export async function getServerSideProps({ context }) {
  const collections = await getAllCollections(context);

  return {
    props: { collections },
  };
}
