import React from "react";
import Head from "next/head";
import ProductsDetails from "../../components/ProductsDetails";
import { getProduct } from "../../lib/shopify";
import { recursiveCatalog } from "../../lib/shopify";

export default function productDetail(product) {
  console.log(product);
  return (
    <>
      <Head>
        <title>Products Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ProductsDetails product={product} />
        </div>
      </main>
    </>
  );
}
export async function getStaticPaths() {
  const products = await recursiveCatalog();

  const paths = products.map((item) => {
    const product = String(item.node.handle);

    return {
      params: { product },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const product = await getProduct(params.product);

  return {
    props: {
      product,
    },
  };
}
