import React from "react";
import Head from "next/head";
import { getAllProducts } from "../../lib/shopify";
import ProductsList from "../../components/ProductsList";

export default function product({ products }) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductsList products={products} />
      </main>
    </>
  );
}
// export async function getStaticProps() {
//   const products = await getAllProducts();

//   return {
//     props: { products },
//   };
// }

export async function getServerSideProps({context}) {
  const products = await getAllProducts(context)
  return {
    props: { products },
  }
}