import React from "react";
import Head from "next/head";
import { getAllProducts } from "../../lib/shopify";

export default function products({ products }) {
  console.log("products", products);
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Product Page</h1>
      </main>
    </>
  );
}
export async function getStaticProps() {
  const products = await getAllProducts();

  return {
    props: { products },
  };
}
