import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useBasket } from "../contexts/BasketContext";

export default function card() {
  const { items } = useBasket();
  console.log("items", items);

  const router = useRouter();

  const total = items.reduce(
    (acc, obj) =>
      acc + Number(obj.product.variants.edges[0].node.priceV2.amount),
    0
  );
  return (
    <div>
      <Head>
        <title>Shopping Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {items.length < 1 && (
          <div className="flex flex-col space-y-7 justify-center items-center md:py-8 md:px-12 px-4 py-6 h-screen">
            <h2 className="whitespace-pre-wrap max-w-prose font-bold text-sm text-black">
              Shopping cart is empty
            </h2>

            <button
              onClick={() => router.push("/product")}
              className="inline-block rounded-sm font-medium text-center py-3 px-4  leading-none bg-black text-white w-full"
            >
              Continue shopping
            </button>
          </div>
        )}
        {items.length > 0 && (
          <>
            <button
              onClick={() => router.push("/product")}
              className="inline-block rounded-sm font-medium text-center py-3 px-4  leading-none bg-black text-white w-full"
            >
              Continue shopping
            </button>
            {items.map((item) => (
              <div key={item.product.id}>
                {/* <h1>{item.product.handle}</h1> */}
                <div className="flex my-5 border">
                  <div className="">
                    <Image
                      src={item.product.images.edges[0].node.originalSrc}
                      width={250}
                      height={250}
                      alt="card"
                    />
                  </div>
                  <div className="p-10">
                    <div className="">
                      <h1 className="font-medium text-xl">
                        {item.product.title}
                      </h1>
                      <div className="">{item.product.description}</div>
                      <div className="">
                        {item.product.variants.edges[0].node.priceV2.amount}₺
                      </div>
                    </div>
                    <button onClick={() => {}}>
                      <span className="bg-black mt-10 text-white inline-block rounded-sm font-medium text-center py-3 px-6 max-w-xl leading-none w-full border">
                        Remove from Card
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            ))}
            <div className="my-5 text-xl text-black">Total Price {total} ₺</div>
          </>
        )}
      </main>
    </div>
  );
}
