import Head from "next/head";
import CollectionsList from "../components/CollectionsList";
import { getAllCollections } from "../lib/shopify";

export default function Home({ collections }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CollectionsList collections={collections} />
      </main>
    </div>
  );
}
export async function getServerSideProps({ context }) {
  const collections = await getAllCollections(context);

  return {
    props: { collections },
  };
}
